services:
  # === Tu servicio n8n (sin cambios) ===
  n8n:
    image: n8nio/n8n:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=http://localhost:5678
      - N8N_LOG_OUTPUT=file
      - N8N_LOG_LEVEL=debug        
      - N8N_LOG_FILE_LOCATION=/logs/n8n.log 
      - N8N_METRICS=true
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./logs:/logs  
    networks:
      - default  

  # === Tu servicio watchtower (sin cambios) ===
  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300

  # === Loki ===
  loki:
    image: grafana/loki:2.7.6
    restart: unless-stopped
    volumes:
      - ./loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default

  # === Promtail ===
  promtail:
    image: grafana/promtail:2.7.6
    user: "0:0"
    restart: unless-stopped
    depends_on:
      - loki
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml:ro
      - ./logs:/logs:ro
      - promtail_positions:/data
    networks:
      - default

  # === Grafana ===
  grafana:
    image: grafana/grafana-enterprise:12.0.1-security-01
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=http://localhost:3000/
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - default

volumes:
  n8n_data:
  loki_data:
  grafana_data:
  promtail_data:
  promtail_positions:
    driver: local

networks:
  default:
    name: auto-n8n
    driver: bridge
