name: Deploy n8n Workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-n8n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Asegurar carpeta n8n_data
        run: mkdir -p ${{ github.workspace }}/n8n_data

      - name: Importar Workflows via n8n CLI
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/workflows:/workflows \
            -v ${{ github.workspace }}/n8n_data:/home/node/.n8n \
            -e N8N_HOST=${{ secrets.N8N_HOST }} \
            -e N8N_AUTH_TOKEN=${{ secrets.N8N_AUTH_TOKEN }} \
            -e N8N_BASIC_AUTH_ACTIVE=true \
            -e N8N_BASIC_AUTH_USER=${{ secrets.N8N_BASIC_AUTH_USER }} \
            -e N8N_BASIC_AUTH_PASSWORD=${{ secrets.N8N_BASIC_AUTH_PASSWORD }} \
            n8nio/n8n:latest \
            n8n import:workflow --separate --input=/workflows
